// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/bodokaiser/entgo-time-mixin/ent/pet"
	"github.com/bodokaiser/entgo-time-mixin/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	petMixin := schema.Pet{}.Mixin()
	petHooks := schema.Pet{}.Hooks()
	pet.Hooks[0] = petHooks[0]
	petMixinFields0 := petMixin[0].Fields()
	_ = petMixinFields0
	petFields := schema.Pet{}.Fields()
	_ = petFields
	// petDescCreatedAt is the schema descriptor for created_at field.
	petDescCreatedAt := petMixinFields0[0].Descriptor()
	// pet.DefaultCreatedAt holds the default value on creation for the created_at field.
	pet.DefaultCreatedAt = petDescCreatedAt.Default.(func() time.Time)
	// petDescUpdatedAt is the schema descriptor for updated_at field.
	petDescUpdatedAt := petMixinFields0[1].Descriptor()
	// pet.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	pet.DefaultUpdatedAt = petDescUpdatedAt.Default.(func() time.Time)
	// pet.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	pet.UpdateDefaultUpdatedAt = petDescUpdatedAt.UpdateDefault.(func() time.Time)
}

const (
	Version = "v0.11.2-0.20220731061215-3f04b0fe6ecb"           // Version of ent codegen.
	Sum     = "h1:gageZoi9MhnzKrmnmyD/on+R+IkNVeYFjBV0Ngehj7c=" // Sum of ent codegen.
)
